### ISSUE TITLE
Save file

### ISSUE THREAD

**Issue by katabamia** [katabamia/Cranberry#9]
Save new (or edited) file to content folder.

this is editor.php function

**Comment by tsukune-ch** [comment]
ext系のFSは同一ディレクトリにファイルが大量にあるとパフォーマンスが悪化してしまうので、この機能を実装するときはディレクトリを分散させて保存するような方法を取ったほうが良さそう。

**Comment by snowhite0804** [comment]
今現在のファイル保存の考え方が `/content/CONTENT_NAME.md` だけど `/content/CONTENT_NAME/index.md` みたいにすれば大丈夫そうですかね

**Comment by tsukune-ch** [comment]
同一のディレクトリにファイルが大量になければいいので、やり方はそんな感じでも問題なさそうー。ただ最大サブディレクトリ数の制限(ext3だと確か32000？)もあるから、ファイル1つ1つにディレクトリを切らずに一定数で次のディレクトリを作るようなやり方でもいいかも。

**Comment by katabamia** [comment]
32000ディレクトリ行く可能性は低いと思うので、ひとまず `/content/CONTENT_NAME/index.md` のような形で実装したいと思います。
もし最大数を超えるようであれば、 `/content2/CONTENT_NAME/index.md` のように親ディレクトリを追加していく形でどうでしょう

**Comment by tsukune-ch** [comment]
よさげだと思います！
